/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mangocannon;

import java.time.LocalDate;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cameron
 */
public class FarmView extends javax.swing.JFrame {
    GlobalVariables globalVar;
    /**
     * Creates new form FarmPickGUI
     */
    public FarmView() {
        initComponents();
    }
    
    public void setGlobalVars(GlobalVariables usingVar) {
        globalVar = usingVar;
        
        //Creates stuff to display in GUI     
        Vector<String> fieldNames = new Vector<String>();
        Vector<String> hasCropPlanted = new Vector<String>();
        Vector<Integer> fieldSize = new Vector<Integer>();
        Vector<String> gpsLocation = new Vector<String>();
        Vector<Double> valuePerM = new Vector<Double>();
        Vector<LocalDate> expectedDates = new Vector<LocalDate>();
        
        for (int i=0; i < globalVar.currentFarm.size(); i++){
            fieldNames.addElement(globalVar.currentFarm.get(i).getFieldName());
            if (globalVar.currentFarm.get(i).getCrop() != null)
            {
                hasCropPlanted.addElement(globalVar.currentFarm.get(i).getCrop().getCropType().getCropName());
                valuePerM.addElement(globalVar.currentFarm.get(i).getCrop().getValue());
                expectedDates.addElement(globalVar.currentFarm.get(i).getCrop().getExpectedHarvest());
            }
            else
            {
                hasCropPlanted.addElement("Not Applicable");
            }
            gpsLocation.add(globalVar.currentFarm.get(i).getFieldStation().getGPS().getGlobalPosition()[0] + ", " + globalVar.currentFarm.get(i).getFieldStation().getGPS().getGlobalPosition()[1]);
            fieldSize.addElement(globalVar.currentFarm.get(i).getGPSBoundary().getFieldArea());            
        }   
        //TableModel for Fields table
        DefaultTableModel modelFields = (DefaultTableModel)tableFields.getModel();        
        modelFields.setRowCount(0);
        modelFields.setColumnCount(0);
        modelFields.addColumn("Fields", fieldNames);        
        modelFields.addColumn("Crop Planted", hasCropPlanted);
        modelFields.addColumn("Estimated Value (£)", valuePerM);
        modelFields.addColumn("Expected Date", expectedDates);
        modelFields.addColumn("Location", gpsLocation);
        modelFields.addColumn("Field Size (Square M)", fieldSize);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tableFields = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tableFields.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableFields);

        jLabel1.setText("Current Orders : Bank View Farm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 943, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FarmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FarmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FarmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FarmView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FarmView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableFields;
    // End of variables declaration//GEN-END:variables
}
